### PR TITLE
ViewHelper and Plugin registered with dependencies

### PR DESCRIPTION
**Pull request by pensiero**
Service locator is not anymore a dependency, but it's injected from factory.
This PR fully support ZF2 >= v2.5.3.

### CODE REVIEW

**Comment by FabianKoestring** [comment]
@neilime Is there anything planned to be released?

**Comment by pensiero** [comment]
@FabianKoestring if you prefer, you can refer to my fork: https://github.com/pensiero/zf2-mobile-detect
The [v2.0.0](https://github.com/pensiero/zf2-mobile-detect/releases/tag/v2.0.0) contains the support to ZF3

**Comment by FabianKoestring** [comment]
@pensiero I think you must create your own composer.json information. There is not branch `2.0` for `neilime/zf2-mobile-detect`.

**Comment by pensiero** [comment]
@FabianKoestring actually if you want you can use this configuration in compose.json:
```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/pensiero/zf2-mobile-detect.git"
    }
  ],
```

**Comment by neilime** [comment]
Thank you @pensiero, I have merge your pull request with some improvments

**Pull request merged**
